
TIVA_DIR = ../..

SRC = master_v1.c buttons.c pwm.c debug.c calibration.c inputs.c control.c display.c OrbitOLED/OrbitOLEDInterface.c $(wildcard OrbitOLED/lib_OrbitOled/*.c)

include $(TIVA_DIR)/tiva.mk
